version: "3.7"

services:
  proxy:
    image: nginx
    environment:
      NGINX_PORT: "${NGINX_PORT:-80}"
      NGINX_DOMAIN: "${NGINX_DOMAIN:-localhost}"
      WIKI_JS_PROTOCOL: "${WIKI_JS_PROTOCOL:-http}"
      WIKI_JS_DOMAIN: "${WIKI_JS_DOMAIN:-app}"
      WIKI_JS_PORT: "${WIKI_JS_PORT:-3000}"
    volumes:
      - ./proxy-nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
  app:
    image: requarks/wiki:2.5
    env_file:
      - .env
  database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: