# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network"

  config.vm.provision :shell, path: "boostrap.sh"

  # use ansible without creating inventory file configuration, in which case hosts configuration: "hosts: all"
  # config.vm.provision :ansible do |ansible|
  #     ansible.playbook = "../ansible/playbook.yml"
  # end

  config.vm.synced_folder "../python/", "/vagrant/python"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 2
  end
end
