version: "3.7"

services:
  app:
    image: requarks/wiki:2.5
    env_file:
      - .env
    ports:
      - "80:3000"
  database:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
