---
- name: Install docker stack
  hosts: testServers
  vars:
    dockerRepositoryUbuntuVersion: "focal"
    dockerTestImage: "hello-world"

  tasks:
    - include: ./playbooks/install-docker-stack-tasks.yml
